/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 19a8144120f3418b4bc79803b3176aa5)
declare namespace Cloudflare {
	interface Env {
		R2_PUBLIC_URL: string;
		FORCE_MINISIGN: boolean;
		API_TOKEN: string;
		ZIGTOOLS_BUILDS: R2Bucket;
		ZIGTOOLS_DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_URL" | "FORCE_MINISIGN" | "API_TOKEN">> {}
}
